FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

# ✅ Copy only requirements.txt first
COPY docker/requirements.txt .

# ✅ Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install lakefs-client
RUN pip install s3fs

# ✅ Copy the rest of your application code after dependencies are installed
COPY . .

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Expose the port Streamlit will run on
EXPOSE 8503

# Command to run when the container starts
CMD ["streamlit", "run", "app.py", "--server.port=8503", "--server.enableCORS=false"]
